Tuple, List
---

In [1]:
x=1
x<100

True

In [2]:
x=[True,True,False]
sum(x)

2

In [3]:
integers = (10, 20, 30)
integers[2]

30

In [8]:
for i in (integers):
    print(i)

10
20
30


In [9]:
x, y, z = integers
x

10

Slicing
---
Part of list

In [10]:
integers[1:]

(20, 30)

In [11]:
integers2= [10, 20, 30]
integers2[2]

30

In [16]:
type(integers),type(integers2)

(tuple, list)

In [17]:
#integers[2]=40
integers2[2]=40
integers2



[10, 20, 40]

Note
---
Test by yourself, assign (mutable) is not worked for tuple!

In [20]:
# append
integers2.append(25)
# what integers2 is now


In [21]:
print("Before sorting: ",integers2)
integers2.sort()

print("after sorting: ",integers2)



Before sorting:  [10, 20, 40, 25]
after sorting:  [10, 20, 25, 40]


dictionary
---
A collection of elements in the form:
```
{ key1:val1,  key2:val2,...}

```
or treated as list with non-integer index.

In [22]:
d = {'name': 'cch', 'ext': 5680}
type(d)

dict

In [23]:
d['ext']

5680

In [24]:
# concatenate 
names=['張山','李氏','王五']
SeqNum=['B100001','B100002','B100003']

List=dict(zip(SeqNum,names))
List

{'B100001': '張山', 'B100002': '李氏', 'B100003': '王五'}

In [27]:
for k,v in List.items():
    print("key: {}, value: {} ".format(k,v) )

key: B100001, value: 張山 
key: B100002, value: 李氏 
key: B100003, value: 王五 


In [28]:
# explode dictionary 

list(List.keys()),list(List.values())

(['B100001', 'B100002', 'B100003'], ['張山', '李氏', '王五'])

In [29]:
List['B100004']='喬八'


In [30]:
List

{'B100001': '張山', 'B100002': '李氏', 'B100003': '王五', 'B100004': '喬八'}

Set
---
different from List

In [31]:
# set
s1 = {'a', 'b'}
type(s1)

set

In [32]:
s2 = {'b', 'c'}
s1.issubset(s2)

False

In [33]:
s1.intersection(s2)

{'b'}

In [34]:
s3 = set(('foo', 'bar', 'foo'))
s3

{'bar', 'foo'}

Input/Output
---

In [35]:
# input/output
f = open('newfile.txt', 'w')   # Open 'newfile.txt' for writing
f.write('Testing\n')           # Here '\n' means new line
f.write('Testing again')
f.close()

Open file in Google drive
---
```python
def open_file_in_colab(filename):
    from google.colab import files
    uploaded = files.upload()
    for fn in uploaded.keys():
        print('User uploaded file "{name}" with length {length} bytes'.format(
            name=fn, length=len(uploaded[fn])))
    return open(fn, 'r')

```

or 
```
import os
from google.colab import drive
 
MOUNTPOINT = "/content/gdrive"
DATADIR = os.path.join(MOUNTPOINT, "MyDrive/2022/111-1/Python_IM")
drive.mount(MOUNTPOINT)

f= open(f"{DATADIR}/test.txt", "r")

```

In [36]:
f = open('newfile.txt', 'r')
out = f.read()
out

'Testing\nTesting again'

In [37]:
# load file

data_file = open('LP.txt', 'r')
for line in data_file:
    name,price = line.split(',')         # Tuple unpacking
    # Add commas to numbers
    print(name.ljust(20) + price)
data_file.close()

Mobile Fidelity     

MFSL-1-201 - Folk Singer - Muddy Waters [1994]  $100

MFSL-1-202 - Atom Heart Mother - Pink Floyd [1994] $116~300

MFSL-1-203 - Tarkus - Emerson Lake & Palmer [1994] $75~100

MFSL-1-204 - Tales of Mystery and Imagination - The Alan Parsons Project [1994] $109~260

MFSL-1-207 - The Unforgettable Fire - U2 [1995] $148~499

MFSL-1-208 - Getz/Gilberto - Stan Getz and Jo o Gilberto [1994] $249.95 ~ 650

MFSL-1-218 - Trilogy - Emerson Lake & Palmer [1995] €149.90 ~ €264.00

MFSL-1-220 - Eric Clapton - Eric Clapton [1995] $87~€250.00

MFSL-1-231 - Murmur - R.E.M. [1995] €150 ~ 294.00 

MFSL-1-235 - Lucille - B.B. King [1995] $130~ €179.00

MFSL-1-238 - Diamonds and Rust - Joan Baez [1995] $60 ~ €298.00

MFSL-1-244 - Teaser and the Firecat - Cat Stevens [1995]  120 

MFSL-1-250 - Toto IV - Toto [1996] €295.00 ~ €684.00

MFSL-1-252 - Old Ways - Neil Young [1996] $ 83 ~ €200.00

MFSL-1-254 - IZITSO - Cat Stevens [1996]  €64.00 ~ €149.00

MFSL-1-258 - Nevermind - Nirvana [19

In [38]:
x_values = [1, 2, 3]  # Some iterable x
for x in x_values:
    # power of variable
    print(x * x)

1
4
9


In [39]:
# again
for i in range(len(x_values)):
    print(x_values[i] * x_values[i])

1
4
9


In [40]:
countries = ('Japan', 'Korea', 'Taiwan')
cities = ('Tokyo', 'Seoul', 'Teipei')
for country, city in zip(countries, cities):
    print(f'The capital of {country} is {city}')

The capital of Japan is Tokyo
The capital of Korea is Seoul
The capital of Taiwan is Teipei


In [41]:

dic1=dict(zip(countries, cities))
dic1

{'Japan': 'Tokyo', 'Korea': 'Seoul', 'Taiwan': 'Teipei'}

In [42]:
for n, c in enumerate(dic1):
    print(f"dic1[{n}] = '{c}'")

dic1[0] = 'Japan'
dic1[1] = 'Korea'
dic1[2] = 'Taiwan'


In [43]:
animals = ['dog', 'cat', 'bird']
plurals = [animal + 's' for animal in animals]
plurals

['dogs', 'cats', 'birds']

In [ ]:
doubles = [2 * x for x in range(8)]
doubles

Diffences between native list and numpy array
---

In [44]:
# again
singles=[ x for x in range(8)]
2*singles

[0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7]

In [1]:
# numpy array
import numpy as np

singles1=np.array([ x for x in range(8)])
2*singles1

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [8]:
from scipy.stats import randint


In [27]:
arr=randint.rvs(0,11, size=10)
#arr.sort()
arr

array([ 5,  5,  7,  1, 10,  9,  4,  1,  9,  1])

In [35]:
np.sort(arr)[len(arr)//2]

5

In [37]:
arr.sort()
arr

array([ 1,  1,  1,  4,  5,  5,  7,  9,  9, 10])

In [46]:
x, y = 1, 2
x < y

True

In [47]:
x = 'yes' if 42 else 'no'
x

'yes'

In [48]:
x = 'yes' if [] else 'no'
x

'no'

In [49]:
1 < 2 and 'f' in 'foo'

True

In [50]:
1 < 2 and 'g' in 'foo'

False

In [51]:
1 < 2 or 'g' in 'foo'

True

function
---
define a `function` to do complicated work:
```python
def func(var1):
    ...
    output=...
    return output
```    

In [52]:
# determine whether variable is negative or not
def f(x):
    if x < 0:
        return 'negative'
    return 'nonnegative'
f(-1)

'negative'

In [53]:
# general function
def f1(x):
    # 3-rd power of input
    return x**3

# embed function (or short function)
f2 = lambda x: x**3

Homework
---

In [54]:
textA='Hello World'
textA[3]

'l'

In [55]:
"r" in textA

True

In [56]:
 isinstance(2,int)

True

In [57]:
 isinstance("a",str)

True

In [58]:
test="a"
test.isalpha()

True

In [59]:
# check statement True or not
testb=1

try:
    test.isalpha()
except:
    print("Input is not character!")


In [60]:
try:
    testb.isalpha()
except:
    print("Input {} is not a alphabet!".format(testb))

Input 1 is not a alphabet!


Now define a function to detect input an integer and one alphabet.

In [61]:
# Answer
def info(intA,chrB):
    if isinstance(intA,int):
       try:
          chrB.isalpha()
          print("your input are: {} and {}".format(intA,chrB))
       except: 
          print("input an integer first, and input a alphabet!") 
    else:
        print("input an integer first!")            

In [62]:
info("a",1)

input an integer first!


In [63]:
info(1,1)

input an integer first, and input a alphabet!


In [64]:
info(1,"a")

your input are: 1 and a
