<big><big><b><div align="center">Mathematics for Management, 2021-2-IM</div></b></big></big>

<h3><div align="left">Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Sequence Number:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div></h3>

<big>
    <big>
 Suppose that 

$$A_{3\times 3} = \left(\begin{array}{ccc}
    1& 2 & 1 \\
    0&-1 & 3 \\
    0&0 & 2 \\
  \end{array}\right)\text{ and }\vec b=\left(\begin{array}{c}
    -1 \\
    2 \\
    2 \\
  \end{array}\right),
  \vec x=\left(\begin{array}{c}
    x_1 \\
    x_2 \\
    x_3 \\
  \end{array}\right)
  $$ 
and 
</big>

<b>a$^\circ$). (20%)</b>  Calculate the transpose of $A$, i.e. $A^T$ and determinant of $A$, $\det(A)$.<br>
<b>b$^\circ$). (10%)</b>  Calculate the matrix product of $A$ and $A^T$, i.e. $AA^T$;<br>
<b>c$^\circ$). (10%)</b>  Also calculate the square of $A$, i.e. $A^2=AA$.<br>
<b>d$^\circ$). (10%)</b>  Solve $\vec x$ if $A\vec x=\vec b$.<br>
<b>e$^\circ$). (30%)</b>  Suppose that $\lambda_1<\lambda_2<\lambda_3$ are eigenvations of $A$ with eigenvectors,
$\vec v_1, \vec v_2, \vec v_3$, respectively. Then find out $\lambda_1,\lambda_2,\lambda_3$ and $\vec v_1, \vec v_2, \vec v_3$.<br>
<b>f$^\circ$). (20%)</b>  (Continued) Suppose that $Q_{3\times3}=[\vec v_1, \vec v_2, \vec v_3]$. Calculate $Q^{-1}$ and $Q^{-1}A^2Q$<br>
<br>
   
</big> 

**Answer**

a. $$A^T=\left(\begin{array}{ccc}
    1& 0 & 0 \\
    2& -1 & 0 \\
    1&3 & 2 \\
  \end{array}\right),\det(A)=-2
$$  
b. $$AA^T = \left(\begin{array}{ccc}
    6& 1 & 2 \\
    1&10 & 6 \\
    2&6 & 4 \\
  \end{array}\right)
$$
c.$$
A^2 = \left(\begin{array}{ccc}
    1& 0 & 9 \\
    0&1 & 3 \\
    0&0 & 4 \\
  \end{array}\right)
$$
d. $$\vec x=\left(\begin{array}{c}
    -4 \\
    1 \\
    1 \\
  \end{array}\right)
$$  
e. 
$$ \lambda_1,\lambda_2,\lambda_2=-1,1,2,
\vec v_1=\left(\begin{array}{c}
    1 \\
    -1 \\
    0 \\
  \end{array}\right),\vec v_2=\left(\begin{array}{c}
    1 \\
    0 \\
    0 \\
  \end{array}\right),\vec v_3=\left(\begin{array}{c}
    3 \\
    1 \\
    1 \\
  \end{array}\right)
$$
f. $$Q^{-1}=\left(\begin{array}{ccc}
    0& 1 & -1 \\
    1&1 & -4 \\
    0&0 & 1 \\
  \end{array}\right),Q^{-1}A^2Q=\left(\begin{array}{ccc}
    1& 0 & 0 \\
    0&1 & 0 \\
    0&0 & 4 \\
  \end{array}\right)
$$  

In [1]:
from scipy.linalg import inv,solve,det,eig
import numpy as np

In [2]:
A = np.array([[1, 2,1], [0, -1,3],[0,0,2]])
b = np.array([[-1],[2],[2]])

In [3]:
A.T

array([[ 1,  0,  0],
       [ 2, -1,  0],
       [ 1,  3,  2]])

In [10]:
det(A)

-2.0

In [11]:
solve(A,b)

array([[-4.],
       [ 1.],
       [ 1.]])

In [12]:
A@A

array([[1, 0, 9],
       [0, 1, 3],
       [0, 0, 4]])

In [12]:
eigenvals,eigenvecs=eig(A)
eigenvals

array([ 1.+0.j, -1.+0.j,  2.+0.j])

In [22]:
np.sort(eigenvals.real)

array([-1.,  1.,  2.])

In [23]:
Q=eigenvecs

array([[ 1.        , -0.70710678,  0.90453403],
       [ 0.        ,  0.70710678,  0.30151134],
       [ 0.        ,  0.        ,  0.30151134]])

In [24]:
Q=eigenvecs
Q_inv=inv(Q)
(Q_inv.dot(A)).dot(Q)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.00000000e+00,  8.92947901e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e+00]])

In [4]:
Q=np.array([[1, 1, 3],
       [-1, 0, 1],
       [0, 0, 1]])

In [9]:
Q1=inv(Q)
Q1

array([[ 0., -1.,  1.],
       [ 1.,  1., -4.],
       [ 0.,  0.,  1.]])

In [11]:
(Q1.dot(A@A)).dot(Q)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 4.]])