<big><big><b><div align="center">Mathematics for Management, 2022-2-IM-1</div></b></big></big>

<h3><div align="left">Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Sequence Number:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div></h3>

<big>
    <big>
 Consider the follows the linear systems:
       
\begin{eqnarray}
    -2x-4y+2z&=&b_1\\
    -2x+y+2z&=&b_2\\
    4x+2y+5z&=&b_3    
\end{eqnarray}        
And the system could be displayed as follows:
$$ A_{3\times3}\vec X_{3\times1}=\vec b_{3\times1}$$
where 

$$\vec b_{3\times1}=\left(\begin{array}{c}
    b_1 \\
    b_2 \\
    b_3 \\
  \end{array}\right),
  \vec X_{3\times1}=\left(\begin{array}{c}
    x \\
    y \\
    z \\
  \end{array}\right)
  $$ 
and 
</big>
<b>a$^\circ$). (10%)</b>  What is $A_{3\times3}$?<br>
<b>b$^\circ$). (15%)</b>  Calculate $1^\circ)$ the transpose of $A_{3\times3}$, i.e. $A_{3\times3}^T$ and $2^\circ)$ determinant of $A_{3\times3}$, $\det(A_{3\times3})$, and $3^\circ)$ trace of $A_{3\times3}$, tr$(A_{3\times3})$.<br>
<b>c$^\circ$). (15%)</b>  If  $A_{3\times3}=S_{3\times3}+P_{3\times3}$ where matrices, $S_{3\times3}, P_{3\times3}$, are symmetry and anti-symmetry respectively. What are $S_{3\times3}, P_{3\times3}$? Also evaluate the differnce of matricies, $S_{3\times3}- P_{3\times3}$<br>
<b>d$^\circ$). (10%)</b>  Solve $\vec X_{3\times1}$ if $A_{3\times3}\vec X_{3\times1}=[2,-1,11]^T$.<br>
<b>e$^\circ$). (30%)</b>  Suppose that $\lambda_1<\lambda_2<\lambda_3$ are eigenvations of $A$ with eigenvectors,
$\vec v_1, \vec v_2, \vec v_3$, respectively. Then find out $\lambda_1,\lambda_2,\lambda_3$ and $\vec v_1, \vec v_2, \vec v_3$.<br>
<b>f$^\circ$). (10%)</b>  (Continued) Suppose that $Q_{3\times3}=[\vec v_1, \vec v_2, \vec v_3]$. Calculate $Q^{-1}$ and $Q^{-1}AQ$.<br>
<b>g$^\circ$). (10%)</b>  Find the characteristic function of $A_{3\times3}$, $\triangle(\lambda)$, i.e. det$( A_{3\times3}-\lambda I_3)$. Also calculate third power of $A,A^{3}$.
<br>
   
</big> 

**Answer**
a).
$$A=\left(\begin{array}{ccc}
    -2& -4 & 2 \\
    -2& 1 & 2 \\
    4&2 & 5 \\
  \end{array}\right)
$$
b. $$A^T=\left(\begin{array}{ccc}
    -2& -2 & 4 \\
    -4& 1 & 2 \\
    2&2 & 5 \\
  \end{array}\right),\det(A)=-90,\text{tr}(A)=4
$$  
c. $S = \left(\begin{array}{ccc}
    -2& -3 & 3 \\
    -3&1 & 2 \\
    3& 2 & 5 \\
  \end{array}\right)
  P = \left(\begin{array}{ccc}
    0& -1 & -1 \\
    1&0 & 0 \\
    1& 0 & 0 \\
  \end{array}\right)
  S-P=\left(\begin{array}{ccc}
    -2& -2 & 4 \\
    -4&1 & 2 \\
    2& 2 & 5 \\
  \end{array}\right)
$


d. $$\vec x=\left(\begin{array}{c}
    2 \\
    -1 \\
    1 \\
  \end{array}\right)
$$ 

e. 
$$ \lambda_1,\lambda_2,\lambda_2=-5,3,6,
\vec v_1=\left(\begin{array}{c}
    2 \\
    1 \\
    -1 \\
  \end{array}\right),\vec v_2=\left(\begin{array}{c}
    2 \\
    -3 \\
    -1 \\
  \end{array}\right),\vec v_3=\left(\begin{array}{c}
    1 \\
    6 \\
    16 \\
  \end{array}\right)
$$
f. $$Q^{-1}=\frac{-1}{132}\left(\begin{array}{ccc}
    -42& -33 & 15 \\
    -22&33 & -11 \\
    -4&0 & -8 \\
  \end{array}\right),Q^{-1}A Q=\left(\begin{array}{ccc}
    -5& 0 & 0 \\
    0&3 & 0 \\
    0&0 & 6 \\
  \end{array}\right)
$$  

g. $\triangle(\lambda)=\lambda^3-4\lambda^2-27\lambda+90, A^3=\left(\begin{array}{ccc}
    -64& -76 & 46 \\
    -14&-11 & 86 \\
    140&38 & 193 \\
  \end{array}\right)$

In [40]:
from scipy.linalg import inv,solve,det,eig
import numpy as np

In [34]:
A = np.array([[-2, -4,2], [-2, 1,2],[4,2,5]])
b = np.array([[2],[-3],[11]])

In [44]:
S=(A+A.T)/2
P=(A-A.T)/2
S,P

(array([[-2., -3.,  3.],
        [-3.,  1.,  2.],
        [ 3.,  2.,  5.]]),
 array([[ 0., -1., -1.],
        [ 1.,  0.,  0.],
        [ 1.,  0.,  0.]]))

In [35]:
solve(A,b)

array([[ 2.],
       [-1.],
       [ 1.]])

In [12]:
A@A

array([[1, 0, 9],
       [0, 1, 3],
       [0, 0, 4]])

In [24]:
eigenvals,eigenvecs=eig(A)
eigenvals.real

array([-5.,  3.,  6.])

In [27]:
np.sort(eigenvals.real)

array([-5.,  3.,  6.])

In [26]:
Q=eigenvecs
Q  

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

$$\lambda_1=-5, \vec v_1=\left(\begin{array}{c}
    2 \\
    1 \\
    -1 \\
  \end{array}\right),
  \lambda_2=3, \vec v_2=\left(\begin{array}{c}
    2 \\
    -3 \\
    -1 \\
  \end{array}\right),
  \lambda_3=6, \vec v_3=\left(\begin{array}{c}
    1 \\
    6 \\
    16 \\
  \end{array}\right),  
  $$
  $$Q=[\vec v_1,\vec v_2,\vec v_3]=\left(\begin{array}{ccc}
    2 &2 &1 \\
    1 &-3  &6\\
    -1 &-1 &16\\
  \end{array}\right)
  $$

In [45]:
Q = np.array([[2, 2,1], [1, -3,6],[-1,-1,16]])
Q1=inv(Q)
Q1

array([[ 0.31818182,  0.25      , -0.11363636],
       [ 0.16666667, -0.25      ,  0.08333333],
       [ 0.03030303,  0.        ,  0.06060606]])

In [48]:
det(Q),det(Q)*Q1

(-132.0,
 array([[-42., -33.,  15.],
        [-22.,  33., -11.],
        [ -4.,  -0.,  -8.]]))

In [31]:
Q1.dot(A).dot(Q)

array([[-5.00000000e+00,  3.33066907e-16, -1.77635684e-15],
       [-1.11022302e-16,  3.00000000e+00,  1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  6.00000000e+00]])

In [4]:
Q=np.array([[1, 1, 3],
       [-1, 0, 1],
       [0, 0, 1]])

In [9]:
Q1=inv(Q)
Q1

array([[ 0., -1.,  1.],
       [ 1.,  1., -4.],
       [ 0.,  0.,  1.]])

In [36]:
A@A@A

array([[-64, -76,  46],
       [-14, -11,  86],
       [140,  38, 193]])